language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시되었을 때 수행하는 명령어
script: "./gradlew clean build"

# deploy 명령어가 실행되기 전에 수행
before_deploy:
  - zip -r webservice *
  - mkdir -p deploy
  - mv webservice.zip deploy/webservice.zip

# S3로 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위들을 선언한다.
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: webservice-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리로써, 해당 위치의 파일들만 S3로 전송
    wait-until-deployed: true
    on:
      all_branches: true # 깃에서 디폴트로 정해진 branch가 master로 설정되어 있는데, 해당 라인이 있으면 다른 브랜치에도 권한이 허용된다.

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: webservice-springboot-build
    key: webservice.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: webservice # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - cer3@ajou.ac.kr
